name: nt-193
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - pip=23.2.1
  - conda=23.9.0
  - python=3.9.16
  - openssl=3.0.11
  - sqlite=3.41.2
  - readline=8.2
  - zlib=1.2.13
  - requests=2.31.0
  - urllib3=1.26.16
